Add an initial Hacktoberfest page
gradle/community pull request #56
Opened 2024-08-08 19:23 UTC by oleg-nenashev

2024-08-08 20:38 UTC, lkasso requested changes

2024-08-08 20:38 UTC, lkasso commented on docs/events/README.md
> +and to offer nice special-edition swag to the key contributors.
```suggestion
and to offer special-edition swag to lucky participants.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/README.md
>  ## Be Informed
```suggestion
## Stay Informed
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +[Hacktoberfest](https://hacktoberfest.com/) is a month-long celebration of open-source projects, their maintainers, and the entire community of contributors.
```suggestion
[Hacktoberfest](https://hacktoberfest.com/) is a month-long celebration of open-source projects, their maintainers and contributors.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +Many component maintainers from the Gradle ecosystem, e.g. the
```suggestion
Many component maintainers from the Gradle ecosystem, such as the
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +In October, Gradle will participate in Hacktoberfest 2024!
```suggestion
This year, Gradle is participating in Hacktoberfest!
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +This year, we are looking forward to offering a few featured projects, hosting online events for newcomer open-source contributors,
```suggestion
We are looking forward to featuring projects, hosting online events for new open-source contributors,
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +Here are a few projects we have in mind  for the event:
```suggestion
Here are a few projects we have in mind for the event:
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +* Making the Gradle plugins compatible with Gradle Configuration Cache ([list of plugin statuses on GitHub](https://github.com/gradle/gradle/issues/13490))
```suggestion
* Making Gradle plugins compatible with Gradle Configuration Cache ([list of plugin statuses on GitHub](https://github.com/gradle/gradle/issues/13490))
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +* Contributing new Gradle solutions to [Gradle Cookbook](https://community.gradle.org/cookbook/), and plugin documentation improvements
```suggestion
* Contributing new Gradle solutions to the [Gradle Cookbook](https://community.gradle.org/cookbook/)
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +* Contributing new Gradle solutions to [Gradle Cookbook](https://community.gradle.org/cookbook/), and plugin documentation improvements
"plugin documentation improvements" isn't very specific.

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +More featured projects will be added soon,
```suggestion
More featured projects will be added soon.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +In addition to common Hacktoberfest swag,
```suggestion
In addition to our Hacktoberfest swag,
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +    and also a few presentations and office hours for newcomer contributors to open source.
```suggestion
    and also a few presentations and office hours for new contributors to open source.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +## Be Informed
``` suggestion
## Stay Informed
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +where we will be posting the key updates and answering any questions.
```suggestion
where we will be posting key updates and answering questions.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +Also, subscribe to the [newsletter](https://newsletter.gradle.org/) for updates
```suggestion
Subscribe to the [newsletter](https://newsletter.gradle.org/) for updates
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +about the upcoming community events and mentorship programs.
```suggestion
about upcoming community events and mentorship programs.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +maintainers are welcome to add their components if there are contributor guidelines
```suggestion
Maintainers are welcome to add their project if they provide contributor guidelines
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/2024/README.md
> +and some issues that can be taken by contributors.
```suggestion
and issues that can be hacked on by contributors.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/README.md
> +[Hacktoberfest](https://hacktoberfest.com/) is a month-long celebration of open-source projects, their maintainers, and the entire community of contributors.
```suggestion
[Hacktoberfest](https://hacktoberfest.com/) is a month-long celebration of open-source projects, their maintainers, and the global community of contributors.
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/README.md
> +Many component maintainers from the Gradle ecosystem, e.g. the
```suggestion
Many maintainers within the Gradle ecosystem, such as those behind the
```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/README.md
> +In 2024, we plan to participate as an organization,
```suggestion
In 2024, we’re excited to join as an organization```

2024-08-08 20:38 UTC, lkasso commented on docs/events/hacktoberfest/README.md
> +and to offer nice special-edition swag to the key contributors.
```suggestion
and will be offering special-edition swag to key contributors.
```

2024-08-09 05:51 UTC, oleg-nenashev commented on docs/events/README.md
> +and to offer nice special-edition swag to the key contributors.
No luck involved there

2024-08-09 07:42 UTC, merged

2024-08-09 07:49 UTC, oleg-nenashev commented
@lkasso merged it to have content in place. Happy to address comments incrementally

2024-08-09 16:10 UTC, lkasso commented
All good!